-- MySQL Script generated by MySQL Workbench
-- Tue Jan 29 19:01:14 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema id7739388_microsensor
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema id7739388_microsensor
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `id7739388_microsensor` DEFAULT CHARACTER SET utf8 ;
USE `id7739388_microsensor` ;

-- -----------------------------------------------------
-- Table `id7739388_microsensor`.`korisnik`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `id7739388_microsensor`.`korisnik` (
  `id_korisnik` INT NOT NULL AUTO_INCREMENT,
  `ime` VARCHAR(50) NOT NULL,
  `prezime` VARCHAR(50) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `lozinka` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_korisnik`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `id7739388_microsensor`.`zgrada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `id7739388_microsensor`.`zgrada` (
  `id_zgrada` INT NOT NULL AUTO_INCREMENT,
  `naziv` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_zgrada`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `id7739388_microsensor`.`dvorana`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `id7739388_microsensor`.`dvorana` (
  `id_dvorana` INT NOT NULL AUTO_INCREMENT,
  `naziv` VARCHAR(45) NOT NULL,
  `id_zgrada` INT NOT NULL,
  PRIMARY KEY (`id_dvorana`),
  INDEX `fk_dvorana_zgrada1_idx` (`id_zgrada` ASC),
  CONSTRAINT `fk_dvorana_zgrada1`
    FOREIGN KEY (`id_zgrada`)
    REFERENCES `id7739388_microsensor`.`zgrada` (`id_zgrada`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `id7739388_microsensor`.`kolegij`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `id7739388_microsensor`.`kolegij` (
  `id_kolegij` INT NOT NULL AUTO_INCREMENT,
  `naziv` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_kolegij`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `id7739388_microsensor`.`studenti_na_kolegiju`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `id7739388_microsensor`.`studenti_na_kolegiju` (
  `id_kolegij` INT NOT NULL,
  `id_korisnik` INT NOT NULL,
  INDEX `fk_studenti_na_kolegiju_kolegij1_idx` (`id_kolegij` ASC),
  INDEX `fk_studenti_na_kolegiju_korisnik1_idx` (`id_korisnik` ASC),
  PRIMARY KEY (`id_kolegij`, `id_korisnik`),
  CONSTRAINT `fk_studenti_na_kolegiju_kolegij1`
    FOREIGN KEY (`id_kolegij`)
    REFERENCES `id7739388_microsensor`.`kolegij` (`id_kolegij`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_studenti_na_kolegiju_korisnik1`
    FOREIGN KEY (`id_korisnik`)
    REFERENCES `id7739388_microsensor`.`korisnik` (`id_korisnik`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `id7739388_microsensor`.`raspored`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `id7739388_microsensor`.`raspored` (
  `id_raspored` INT NOT NULL AUTO_INCREMENT,
  `id_kolegij` INT NOT NULL,
  `id_dvorana` INT NOT NULL,
  `dan` VARCHAR(45) NOT NULL,
  `pocetak` TIME NOT NULL,
  `kraj` TIME NOT NULL,
  `tip` VARCHAR(45) NULL,
  INDEX `fk_raspored_kolegij1_idx` (`id_kolegij` ASC),
  INDEX `fk_raspored_dvorana1_idx` (`id_dvorana` ASC),
  PRIMARY KEY (`id_raspored`),
  CONSTRAINT `fk_raspored_kolegij1`
    FOREIGN KEY (`id_kolegij`)
    REFERENCES `id7739388_microsensor`.`kolegij` (`id_kolegij`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_raspored_dvorana1`
    FOREIGN KEY (`id_dvorana`)
    REFERENCES `id7739388_microsensor`.`dvorana` (`id_dvorana`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `id7739388_microsensor`.`prisustvo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `id7739388_microsensor`.`prisustvo` (
  `id_raspored` INT NOT NULL,
  `id_korisnik` INT NOT NULL,
  `datum` DATE NOT NULL,
  PRIMARY KEY (`id_raspored`, `id_korisnik`, `datum`),
  INDEX `fk_prisustvo_korisnik1_idx` (`id_korisnik` ASC),
  INDEX `fk_prisustvo_raspored1_idx` (`id_raspored` ASC),
  CONSTRAINT `fk_prisustvo_korisnik1`
    FOREIGN KEY (`id_korisnik`)
    REFERENCES `id7739388_microsensor`.`korisnik` (`id_korisnik`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_prisustvo_raspored1`
    FOREIGN KEY (`id_raspored`)
    REFERENCES `id7739388_microsensor`.`raspored` (`id_raspored`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `id7739388_microsensor`.`mjerenje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `id7739388_microsensor`.`mjerenje` (
  `id_mjerenje` INT NOT NULL AUTO_INCREMENT,
  `temperatura` DECIMAL NULL,
  `vlaznost_zraka` DECIMAL NULL,
  `jacina_svjetlosti` DECIMAL NULL,
  `datum` DATETIME NOT NULL,
  `id_dvorana` INT NOT NULL,
  PRIMARY KEY (`id_mjerenje`),
  INDEX `fk_mjerenje_dvorana1_idx` (`id_dvorana` ASC),
  CONSTRAINT `fk_mjerenje_dvorana1`
    FOREIGN KEY (`id_dvorana`)
    REFERENCES `id7739388_microsensor`.`dvorana` (`id_dvorana`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
